### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by shiroyashik** [TropicalShadow/ArcaneTablePlugin#2]
Paper: 1.20-17
Plugin version: 1.5.0

```
[22:12:28] [Server thread/INFO]: [ArcaneTable] Enabling ArcaneTable v1.5.0
[22:12:28] [Server thread/ERROR]: Error occurred while enabling ArcaneTable v1.5.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at me.tropicalshadow.arcanetable.ArcaneTable.onEnable(ArcaneTable.java:32) ~[ArcaneTable-1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-17]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.jar:git-Paper-17]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.jar:git-Paper-17]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.jar:git-Paper-17]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "20)"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at me.tropicalshadow.arcanetable.utils.VersionUtils.<clinit>(VersionUtils.java:12) ~[ArcaneTable-1.5.0.jar:?]
	... 13 more
[22:12:28] [Server thread/INFO]: [ArcaneTable] Disabling ArcaneTable v1.5.0
[22:12:28] [Server thread/INFO]: [ArcaneTable] [AT] Plugin Disabled
```

[latest.log](https://github.com/TropicalShadow/ArcaneTablePlugin/files/12164973/latest.log)

**Comment by TropicalShadow** [comment]
Thank you for providing the logs,
after looking into the issue i found the cause.

I will edit the code today and publish a new working version.
